---
- hosts: dev
  remote_user: root
  vars_files:
      - vars/main.yml
  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600
      when: ansible_os_family == 'Debian'
      changed_when: false

    - name: Install cron (Debian).
      apt: name=cron state=present
      when: ansible_os_family == 'Debian'

  roles:
    - common
    - ansible-role-certbot
    - ansible-role-nginx
    - ansible-role-htpasswd

  tasks:
    - name: Flush handlers in case any configs have changed.
      meta: flush_handlers
    - shell: echo 'GITHUB_ACCESS_TOKEN={{ lookup("env", "GITHUB_ACCESS_TOKEN") }}' >> /etc/environment

    - name: Test secure connection to SSL domain.
      uri:
        url: https://devdinsic:supersecure@dev.numerique.gouv.fr
        status_code: 200
      delegate_to: localhost
      become: no
